[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
demo = "FncXY9fhaEx2Tb2rcqetJc2yFNDKDqU2QL7pDKzc7sJX"
demo2 = "AN5RLVdXviuRtCs8jhMcWq4HgzkB3hTNjaWq1U6c8qCS"
demo3 = "GtEeAt513NhkteU1z1boBsZXwTeiGXVf3kRiAjk79nt8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/demo.ts"
script = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/script.ts"
