[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
demo = "98cf3XgFWdycZrwuXyZJsWwFip8FyoH3kn6eFLPdcNB2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/demo.ts"
script = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/script.ts"
